CREATE TABLE 'notes'.'note' (
  'NOTE_ID' INT NOT NULL,
  'FACE_VALUE' INT NULL,
  'DISCOUNT' FLOAT NULL,
  'PERFORMANCE' VARCHAR(45) NULL,
  'NOTE_TYPE' VARCHAR(45) NOT NULL,
  'NOTE_POSITION' INT NULL,
  'PROP_ID' INT NULL,
  'BORROWER_TYPE' VARCHAR(45) NULL,
  'USER_USER_ID' INT NULL,
  'MONTHS_TO_MATURITY' INT NULL,
  'INTREST_RATE' FLOAT NULL,
  'NEXT_INTREST_ADJUSTMENT_DATE' DATE NULL,
  'INTREST_RATE_ADJUSTMENT_RULE' VARCHAR(45) NULL,
  'NoteSearchID' VARCHAR(45) NULL,
  'USER_SCORE' INT NULL,
  'systemScore' INT NULL,
  'VENDOR_NOTE_ID' VARCHAR(45) NULL,
  PRIMARY KEY ('NOTE_ID'),
  INDEX 'note_id' ('NOTE_ID' ASC));
  
 ALTER TABLE 'notes'.'note' 
	ADD INDEX 'fk_NoteType_idx' ('NOTE_TYPE' ASC);
ALTER TABLE 'notes'.'note' 
ADD CONSTRAINT 'fk_NoteType'
  FOREIGN KEY ('NOTE_TYPE')
  REFERENCES 'notes'.'notetype' ('NOTE_TYPE')
  ON UPDATE NO ACTION;