CREATE TABLE notes.note (
  NID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOTE_ID VARCHAR(15) NOT NULL UNIQUE,
  FACE_VALUE INT NULL,
  DISCOUNT FLOAT NULL,
  PERFORMANCE VARCHAR(45) NULL,
  NOTE_TYPE VARCHAR(45) NOT NULL,
  NOTE_POSITION INT NULL,
  PROP_ID VARCHAR(15) NOT NULL,
  BORROWER_TYPE VARCHAR(45) NULL,
  USER_USER_ID INT NULL,
  MONTHS_TO_MATURITY INT NULL,
  INTREST_RATE FLOAT NULL,
  NEXT_INTREST_ADJUSTMENT_DATE DATE NULL,
  INTREST_RATE_ADJUSTMENT_RULE VARCHAR(45) NULL,
  NoteSearchID VARCHAR(45) NULL,
  USER_SCORE INT NULL,
  systemScore INT NULL,
  VENDOR_NOTE_ID VARCHAR(45) NULL,
  DATE_OF_NOTE DATE NOT NULL,
  UNPAID_PRIN_BAL INT NULL,
  RATE INT NULL,
  PDI_PAY INT NULL,
  TDI_PAY INT NULL,
  ORIGINAL_TERM INT NULL,
  UPDATED_DATE_TIME DATE NULL,
  UPDATED_BY  VARCHAR(45) NULL,
  CREATED_DATE_TIME DATE NULL,
  CREATED_BY  VARCHAR(45) NULL,
  INDEX fk_notetype_idx (NOTE_TYPE ASC),
  CONSTRAINT fk_notetype FOREIGN KEY (NOTE_TYPE)
  REFERENCES notes.note_type (NOTE_TYPE)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  INDEX fk_propid_idx (PROP_ID ASC),
  CONSTRAINT fk_propid FOREIGN KEY (PROP_ID)
  REFERENCES notes.property (PROP_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  INDEX fk_borrtype_idx (BORROWER_TYPE ASC),
  CONSTRAINT fk_borrowType FOREIGN KEY (BORROWER_TYPE)
  REFERENCES notes.borrower_type (BORROWER_TYPE)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,

  );
  
  