
  CREATE TABLE 'notes'.'property' (
  'PROP_ID' INT NOT NULL,
  'AREA_ID' INT NULL,
  'PROP_NAME' VARCHAR(45) NULL,
  'PROPERTY_TYPE' VARCHAR(45) NULL,
  'PROP_DESC' VARCHAR(45) NULL,
  'STREET' VARCHAR(45) NULL,
  'CITY' VARCHAR(45) NULL,
  'STATE' VARCHAR(45) NULL,
  'ZIP' INT NULL,
  'AGE' INT NULL,
  'SIZE_SF' INT NULL,
  'SUBDIVIDABLE' TINYINT NULL,
  'OTH_HIGH_PRIO_DEBT' INT NULL,
  'OTH_LOW_PRIO_DEBT' INT NULL,
  'OTH_MONTH_EXPENSE' INT NULL,
  PRIMARY KEY ('PROP_ID'));

  
  ALTER TABLE 'notes'.'property' 
ADD INDEX 'gk_propType_idx' ('PROPERTY_TYPE' ASC),
ADD INDEX 'fk_areaid_idx' ('AREA_ID' ASC);
ALTER TABLE 'notes'.'property' 
ADD CONSTRAINT 'fk_propType'
  FOREIGN KEY ('PROPERTY_TYPE')
  REFERENCES 'notes'.'property_type' ('PROPERTY_TYPE')
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT 'fk_areaid'
  FOREIGN KEY ('AREA_ID')
  REFERENCES 'notes'.'area' ('AREA_ID')
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

  
  