CREATE TABLE notes.property_type (
  P_TYPE_ID INTEGER NOT NULL,
  PROPERTY_TYPE VARCHAR(15) NOT NULL,
  DESCRIPTION VARCHAR(45) NULL,
  UPDATED_DATE_TIME DATE NULL,
  UPDATED_BY  VARCHAR(45) NULL,
  CREATED_DATE_TIME DATE NULL,
  CREATED_BY  VARCHAR(45) NULL,
  PRIMARY KEY (P_TYPE_ID),
  UNIQUE INDEX NOTE_TYPE_UNIQUE (PROPERTY_TYPE ASC));
  